# Generated by Django 5.2.8 on 2025-11-20 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_category_description_product_created_at_and_more'),
    ]

    operations = [
    ]
