# Generated by Django 5.2.8 on 2025-11-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_image_created_at'),
        ('products', '0004_auto_20251120_2004'),
    ]

    operations = [
    ]
